#!/bin/bash

## this script is only run if actual change to domain is detected (there is
## no path question for this app - it only ever installs at domain root)
## new domain is available via $domain (or $new_domain if you want to be explicit)
## old value is available via $old_domain

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# UPDATE SYSTEMD CONFIGURATION
#=================================================
ynh_script_progression "Updating $app's systemd configuration..."

# ORIGIN is derived from $domain, so the unit needs regenerating on domain change
ynh_config_add_systemd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --wait_until="Server ready" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
