#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download the source code to /tmp/$app because we need just some folder for building the app
ynh_setup_source --dest_dir="/tmp/$app"

mkdir -p "$install_dir/backend"
mkdir -p "$install_dir/web"

pushd "/tmp/$app"
    cp -r backend/* $install_dir/backend/
    cp -r frontend/* $install_dir/web/
popd

rm -rf /tmp/$app

#=================================================
# SETUP THE APP
#=================================================
chown -R "$app:www-data" "$install_dir"

pushd $install_dir
    # Install backend dependencies
    ynh_script_progression "Installing backend dependencies..."
    ynh_replace_regex --match="PyYAML==5.4.1" --replace="PyYAML==6.0.1" --file="$install_dir/backend/requirements.txt"
    ynh_exec_as_app python3 -m venv "$install_dir/backend/venv"
    ynh_hide_warnings ynh_exec_as_app "$install_dir/backend/venv/bin/pip" install --no-cache-dir --upgrade pip setuptools wheel
    ynh_hide_warnings ynh_exec_as_app "$install_dir/backend/venv/bin/pip" install --no-cache-dir --upgrade -r "$install_dir/backend/requirements.txt"

    # Install frontend dependencies
    ynh_script_progression "Installing frontend dependencies..."
    pushd "$install_dir/web"
        ynh_hide_warnings ynh_exec_as_app npm install

        ynh_script_progression "Building frontend..."
        ynh_hide_warnings ynh_exec_as_app npm run build
    popd
popd

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

# create log directory in data_dir
mkdir -p "/var/log/$app"
ln -s "/var/log/$app" "$data_dir/logs"

# create config directory in data_dir
mkdir -p "$data_dir/config"
chmod 755 "$data_dir/config"
chown -R "$app:$app" "$data_dir/config"
ln -s "$data_dir/config" "$install_dir/backend/config"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd
yunohost service add "$app" --description="Profilarr backend" --log="/var/log/$app/backend.log"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate "/var/log/$app/"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
