#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

### Settings are automatically loaded as bash variables
### in every app script context, therefore typically these will exist:
### - $domain
### - $path
### - $language
### - $install_dir
### - $port
### ...

### For remove operations:
### - the core will deprovision every resource defined in the manifest **after** this script is ran
### this includes removing the install directory, and data directory (if --purge was used)

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

# Stop the systemd service before removing it
ynh_systemctl --service="$app" --action="stop"

#=================================================
# REMOVE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

### This should be a symetric version of what happens in the install script

# Remove logrotate configuration
ynh_config_remove_logrotate

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status "$app" >/dev/null; then
    yunohost service remove "$app"
fi

# Remove systemd service configuration
ynh_config_remove_systemd

# Remove NGINX configuration
ynh_config_remove_nginx

#=================================================
# REMOVE APP-SPECIFIC FILES
#=================================================

# Remove PID files created by start.sh
ynh_safe_rm "/tmp/$app-backend.pid"
ynh_safe_rm "/tmp/$app-frontend.pid"

# Remove the symlink to logs directory (if it exists)
ynh_safe_rm "$data_dir/logs"
ynh_safe_rm "$install_dir/backend/config"

# Remove other various files specific to the app... such as:
ynh_safe_rm "/etc/cron.d/$app"
ynh_safe_rm "/etc/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
